CREATE TABLE [sourceNuudlBIZ].[dimdimproduct] (
    [NUUDL_SourceCreated]             DATETIME2 (7)  NULL,
    [NUUDL_SourceUpdated]             DATETIME2 (7)  NULL,
    [ProductKey]                      INT            NULL,
    [DimEditor_Updated_TS]            DATETIME2 (7)  NULL,
    [DimEditor_Created_TS]            DATETIME2 (7)  NULL,
    [DimEditor_Created_By]            NVARCHAR (300) NULL,
    [ProductID]                       NVARCHAR (36)  NULL,
    [SourceSystem]                    NVARCHAR (300) NULL,
    [Downstream]                      INT            NULL,
    [ETL_AntalLinier]                 INT            NULL,
    [ETL_FlowRelevant]                NVARCHAR (300) NULL,
    [ETL_ProduktInfo]                 NVARCHAR (300) NULL,
    [ETL_ProduktKobling]              NVARCHAR (300) NULL,
    [ETL_TekstRelevant]               NVARCHAR (300) NULL,
    [IsWholesale]                     NVARCHAR (300) NULL,
    [ProductBrandCategory]            NVARCHAR (300) NULL,
    [ProductCategory]                 NVARCHAR (300) NULL,
    [ProductChange]                   NVARCHAR (300) NULL,
    [ProductChangeCategory]           NVARCHAR (300) NULL,
    [ProductMainCategory]             NVARCHAR (300) NULL,
    [ProductName]                     NVARCHAR (300) NULL,
    [ProductNetworkTechnology]        NVARCHAR (300) NULL,
    [ProductSubCategory]              NVARCHAR (300) NULL,
    [ProductTargetCustomer]           NVARCHAR (300) NULL,
    [ProductTransmissionTechnology]   NVARCHAR (300) NULL,
    [ProductType]                     NVARCHAR (300) NULL,
    [SalesEffectiveDate]              DATETIME2 (7)  NULL,
    [SalesExperiationDate]            DATETIME2 (7)  NULL,
    [ServiceType]                     NVARCHAR (300) NULL,
    [SourceCreatedDate]               DATETIME2 (7)  NULL,
    [SourceEffectiveDate]             DATETIME2 (7)  NULL,
    [SourceExpirationDate]            DATETIME2 (7)  NULL,
    [SourceUpdatedBy]                 NVARCHAR (300) NULL,
    [SourceUpdatedDate]               DATETIME2 (7)  NULL,
    [Upstream]                        INT            NULL,
    [NUUDL_ID]                        BIGINT         NOT NULL,
    [NUUDL_ValidFrom]                 DATETIME2 (7)  NULL,
    [NUUDL_ValidTo]                   DATETIME2 (7)  NULL,
    [NUUDL_IsCurrent]                 BIT            NULL,
    [BIZ_BatchCreatedID]              INT            NULL,
    [BIZ_BatchUpdatedID]              INT            NULL,
    [NUUDL_PKLatest]                  BIT            NULL,
    [SAF_Attr]                        NVARCHAR (300) NULL,
    [ETL_SAFFlowrelevant]             NVARCHAR (300) NULL,
    [ETL_SAFFlowrelevantDate]         NVARCHAR (300) NULL,
    [Niv1]                            INT            NULL,
    [Niv2]                            INT            NULL,
    [Niv3]                            INT            NULL,
    [Niv4]                            INT            NULL,
    [ProductSubCategory2]             NVARCHAR (300) NULL,
    [BellisPrioritet]                 INT            NULL,
    [Bemaerkning]                     NVARCHAR (300) NULL,
    [CallDirectionFrom]               NVARCHAR (300) NULL,
    [CallDirectionTo]                 NVARCHAR (300) NULL,
    [Landekode]                       NVARCHAR (300) NULL,
    [Source_Created_By]               NVARCHAR (300) NULL,
    [Source_Updated_By]               NVARCHAR (300) NULL,
    [TrafficAddon]                    NVARCHAR (300) NULL,
    [Volumetype]                      NVARCHAR (300) NULL,
    [BundleType]                      NVARCHAR (300) NULL,
    [Technology]                      NVARCHAR (300) NULL,
    [ProductWeight]                   INT            NULL,
    [NUUDL_BaseSourceFilename]        NVARCHAR (300) NULL,
    [NUUDL_BaseBatchID]               INT            NULL,
    [NUUDL_BaseProcessedTimestamp]    NVARCHAR (300) NULL,
    [NUUDL_CuratedBatchID]            INT            NULL,
    [NUUDL_CuratedProcessedTimestamp] NVARCHAR (300) NULL,
    [DWCreatedDate]                   DATETIME2 (7)  DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_dimdimproduct] PRIMARY KEY NONCLUSTERED ([NUUDL_ID] ASC)
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_dimdimproduct]
    ON [sourceNuudlBIZ].[dimdimproduct];

