CREATE TABLE [sourceNuudlBIZ].[pdindividge_History] (
    [NUUDL_SourceCreated]             DATETIME2 (7)  NULL,
    [NUUDL_SourceUpdated]             DATETIME2 (7)  NULL,
    [FIRMA]                           NVARCHAR (300) NULL,
    [ENHED]                           NVARCHAR (300) NULL,
    [VIRKNR]                          NVARCHAR (300) NULL,
    [LOENNR]                          NVARCHAR (300) NULL,
    [LOEBENR]                         DECIMAL (2)    NULL,
    [STATUS]                          NVARCHAR (300) NULL,
    [ANUMMER]                         NVARCHAR (300) NULL,
    [EMAIL]                           NVARCHAR (300) NULL,
    [STEDNR]                          NVARCHAR (300) NULL,
    [AONR]                            NVARCHAR (300) NULL,
    [KONTORFORK]                      NVARCHAR (300) NULL,
    [KONTORNAVN]                      NVARCHAR (300) NULL,
    [FYSADR]                          NVARCHAR (300) NULL,
    [POSTADR]                         NVARCHAR (300) NULL,
    [STIL_KODE]                       NVARCHAR (300) NULL,
    [INITIALER]                       NVARCHAR (300) NULL,
    [NAVN]                            NVARCHAR (300) NULL,
    [FORNAVN]                         NVARCHAR (300) NULL,
    [MELLEMNAVN]                      NVARCHAR (300) NULL,
    [EFTERNAVN]                       NVARCHAR (300) NULL,
    [ADRESSE]                         NVARCHAR (300) NULL,
    [ADRLIN_1]                        NVARCHAR (300) NULL,
    [ADRLIN_2]                        NVARCHAR (300) NULL,
    [ADRLIN_3]                        NVARCHAR (300) NULL,
    [POSTNR]                          NVARCHAR (300) NULL,
    [KOEN]                            NVARCHAR (300) NULL,
    [ANS_DATO]                        DATETIME2 (7)  NULL,
    [AFG_DATO]                        DATETIME2 (7)  NULL,
    [FOD_DATO]                        DATETIME2 (7)  NULL,
    [START_ORLOV]                     DATETIME2 (7)  NULL,
    [SLUT_ORLOV]                      DATETIME2 (7)  NULL,
    [OMRAADE]                         NVARCHAR (300) NULL,
    [TLFLOK]                          NVARCHAR (300) NULL,
    [TLFDIR]                          NVARCHAR (300) NULL,
    [TLFMOB]                          NVARCHAR (300) NULL,
    [TLFALT]                          NVARCHAR (300) NULL,
    [TLFFAX]                          NVARCHAR (300) NULL,
    [TLFOPS]                          NVARCHAR (300) NULL,
    [TLFUDL]                          NVARCHAR (300) NULL,
    [TJEGREN]                         NVARCHAR (300) NULL,
    [KATEGORI]                        NVARCHAR (300) NULL,
    [AFLFORM]                         DECIMAL (3)    NULL,
    [TILHOER]                         NVARCHAR (300) NULL,
    [ARBSTEDKD]                       NVARCHAR (300) NULL,
    [AENDRET]                         DATETIME2 (7)  NULL,
    [OPDATERET]                       DATETIME2 (7)  NULL,
    [NORMTID]                         NVARCHAR (36)  NULL,
    [TRGRUPPE]                        NVARCHAR (300) NULL,
    [BANKREGNR]                       NVARCHAR (300) NULL,
    [BANKKONTONR]                     NVARCHAR (300) NULL,
    [FAGGRUPPE]                       NVARCHAR (300) NULL,
    [NUUDL_ID]                        BIGINT         NOT NULL,
    [NUUDL_ValidFrom]                 DATETIME2 (7)  NULL,
    [NUUDL_ValidTo]                   DATETIME2 (7)  NULL,
    [NUUDL_IsCurrent]                 BIT            NULL,
    [BIZ_BatchCreatedID]              INT            NULL,
    [BIZ_BatchUpdatedID]              INT            NULL,
    [NUUDL_PKLatest]                  BIT            NULL,
    [NUUDL_BaseSourceFilename]        NVARCHAR (300) NULL,
    [NUUDL_BaseBatchID]               INT            NULL,
    [NUUDL_BaseProcessedTimestamp]    NVARCHAR (300) NULL,
    [NUUDL_CuratedBatchID]            INT            NULL,
    [NUUDL_CuratedProcessedTimestamp] NVARCHAR (300) NULL,
    [DWIsCurrent]                     BIT            NULL,
    [DWValidFromDate]                 DATETIME2 (7)  NOT NULL,
    [DWValidToDate]                   DATETIME2 (7)  NULL,
    [DWCreatedDate]                   DATETIME2 (7)  NULL,
    [DWModifiedDate]                  DATETIME2 (7)  NULL,
    [DWIsDeletedInSource]             BIT            NULL,
    [DWDeletedInSourceDate]           DATETIME2 (7)  NULL,
    CONSTRAINT [PK_pdindividge_History] PRIMARY KEY NONCLUSTERED ([NUUDL_ID] ASC, [DWValidFromDate] ASC)
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_pdindividge_History]
    ON [sourceNuudlBIZ].[pdindividge_History];

