CREATE TABLE [sourceNuudlDawn].[cpmnrmltroubleticket] (
    [approval_reason]                 NVARCHAR (500)  NULL,
    [channel_id]                      NVARCHAR (50)   NULL,
    [closed_by_date]                  DATETIME2 (7)   NULL,
    [closed_by_user_id]               NVARCHAR (50)   NULL,
    [closed_by_user_name]             NVARCHAR (500)  NULL,
    [closure_code]                    NVARCHAR (500)  NULL,
    [created_by_date]                 DATETIME2 (7)   NULL,
    [created_by_user_id]              NVARCHAR (50)   NULL,
    [created_by_user_name]            NVARCHAR (500)  NULL,
    [description]                     NVARCHAR (MAX)  NULL,
    [dispute_item]                    NVARCHAR (MAX)  NULL,
    [expected_resolution_date]        DATETIME2 (7)   NULL,
    [extended_attributes]             NVARCHAR (MAX)  NULL,
    [external_id]                     NVARCHAR (50)   NULL,
    [first_resolution_date]           DATETIME2 (7)   NULL,
    [group_assignee_id]               NVARCHAR (50)   NULL,
    [group_assignee_name]             NVARCHAR (500)  NULL,
    [group_assignee_type]             NVARCHAR (500)  NULL,
    [id]                              NVARCHAR (50)   NULL,
    [is_solution_visible_for_contact] BIT             NULL,
    [last_approved_by_date]           DATETIME2 (7)   NULL,
    [last_approved_by_user_id]        NVARCHAR (50)   NULL,
    [last_approved_by_user_name]      NVARCHAR (500)  NULL,
    [last_updated_by_date]            DATETIME2 (7)   NULL,
    [last_updated_by_user_id]         NVARCHAR (50)   NULL,
    [last_updated_by_user_name]       NVARCHAR (500)  NULL,
    [name]                            NVARCHAR (500)  NULL,
    [op]                              NVARCHAR (500)  NULL,
    [priority]                        NVARCHAR (500)  NULL,
    [problem_start_date]              DATETIME2 (7)   NULL,
    [project_id]                      NVARCHAR (50)   NULL,
    [project_name]                    NVARCHAR (500)  NULL,
    [reporter_id]                     NVARCHAR (50)   NULL,
    [reporter_name]                   NVARCHAR (500)  NULL,
    [reporter_type]                   NVARCHAR (500)  NULL,
    [requested_resolution_date]       DATETIME2 (7)   NULL,
    [resolution_reason]               NVARCHAR (500)  NULL,
    [resolved_by_date]                DATETIME2 (7)   NULL,
    [resolved_by_user_id]             NVARCHAR (50)   NULL,
    [resolved_by_user_name]           NVARCHAR (500)  NULL,
    [severity]                        NVARCHAR (500)  NULL,
    [solution]                        NVARCHAR (500)  NULL,
    [status]                          NVARCHAR (500)  NULL,
    [status_change_date]              DATETIME2 (7)   NULL,
    [status_change_reason]            NVARCHAR (500)  NULL,
    [tags]                            NVARCHAR (500)  NULL,
    [ticket_category]                 NVARCHAR (500)  NULL,
    [ticket_type]                     NVARCHAR (500)  NULL,
    [total_disputed_amount]           DECIMAL (10)    NULL,
    [total_initial_amount]            DECIMAL (10)    NULL,
    [ts_ms]                           BIGINT          NULL,
    [user_assignee_id]                NVARCHAR (50)   NULL,
    [user_assignee_name]              NVARCHAR (500)  NULL,
    [user_assignee_type]              NVARCHAR (500)  NULL,
    [version]                         DECIMAL (10)    NULL,
    [NUUDL_CuratedBatchID]            INT             NULL,
    [NUUDL_CuratedProcessedTimestamp] NVARCHAR (500)  NULL,
    [NUUDL_IsCurrent]                 BIT             NULL,
    [NUUDL_ValidFrom]                 DATETIME2 (7)   NULL,
    [NUUDL_ValidTo]                   DATETIME2 (7)   NULL,
    [NUUDL_ID]                        BIGINT          NOT NULL,
    [DWCreatedDate]                   DATETIME2 (7)   DEFAULT (getdate()) NULL,
    [NUUDL_IsDeleted]                 BIT             NULL,
    [NUUDL_DeleteType]                NVARCHAR (4000) NULL,
    [NUUDL_IsLatest]                  BIT             NULL,
    CONSTRAINT [PK_cpmnrmltroubleticket] PRIMARY KEY NONCLUSTERED ([NUUDL_ID] ASC)
);




GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_cpmnrmltroubleticket]
    ON [sourceNuudlDawn].[cpmnrmltroubleticket];



