
CREATE VIEW [sourceNuuDataCubusMasterDataView].[CubusMasterData_DimEmployee_History]
AS
SELECT 
	[EmployeeKey] ,
	[SRC_DW_ID_DimEmployeeWork] ,
	[SRC_DW_AuditKey] ,
	[SRC_DW_Batch_Created_ID] ,
	[SRC_DW_Batch_Updated_ID] ,
	[SRC_DW_CreateDate] ,
	[SRC_DW_UpdateDate] ,
	[SRC_DW_Valid_From] ,
	[SRC_DW_Valid_To] ,
	[SRC_DW_EarlyArrived] ,
	[SRC_DW_IsCurrent] ,
	[SRC_DW_IsDeleted] ,
	[SRC_DW_CRC] ,
	[Source_Updated_TS] ,
	[Source_Created_TS] ,
	[Source_Updated_By] ,
	[Source_Created_By] ,
	[EmployeeID] ,
	[EmployeeRecord] ,
	[SourceSystem] ,
	[JobIndicator] ,
	[EmployeeStatus] ,
	[Sex] ,
	[BirthDate] ,
	[FirstName] ,
	[LastName] ,
	[Name] ,
	[LocalPhone] ,
	[MobilePhone] ,
	[FAX] ,
	[WorkplacePhone] ,
	[AlternativePhone] ,
	[RoomNumber] ,
	[PostalRoomNumber] ,
	[Email] ,
	[UserID] ,
	[SeniorityDate] ,
	[AnniversaryDate] ,
	[StandardHours] ,
	[OriginalHireDate] ,
	[LatestHireDate] ,
	[TerminationDate] ,
	[LocationID] ,
	[WorkAddress] ,
	[WorkZipCode] ,
	[WorkPostalDistrict] ,
	[BusinessTitleCode] ,
	[BusinessTitle] ,
	[BusinessTitleShort] ,
	[BusinessStatisticsCode] ,
	[BusinessFunction] ,
	[JobStatus] ,
	[JobCode] ,
	[JobCodeDescription] ,
	[EmployeeClass] ,
	[SalaryAdminPlan] ,
	[SalaryGrade] ,
	[PayGroup] ,
	[SalaryType] ,
	[EmployeeType] ,
	[DepartmentID] ,
	[DepartmentDescription] ,
	[DepartmentDescriptionShort] ,
	[ManagerEmployeeID] ,
	[AONR] ,
	[Company] ,
	[CompanyDescription] ,
	[CompanyDescriptionShort] ,
	[EmployeeTypeCode] ,
	[TerminationInfo] ,
	[EmployeeStatusDescription] ,
	[SexDescription] ,
	[SkillGroup] ,
	[IsManager] ,
	[SquadID] ,
	[SquadDescription] ,
	[SquadDescriptionShort] ,
	[IsAgileCoach] ,
	[IsProductOwner] ,
	[ApprovedEmailDomain] ,
	[ChapterAreaID] ,
	[ChapterAreaDescription] ,
	[ChapterAreaDescriptionShort] ,
	[SRC_DWIsCurrent] ,
	[SRC_DWValidFromDate] ,
	[SRC_DWValidToDate] ,
	[SRC_DWCreatedDate] ,
	[SRC_DWModifiedDate] ,
	[SRC_DWIsDeletedInSource] ,
	[SRC_DWDeletedInSourceDate] 
	,[DWIsCurrent]
	,[DWValidFromDate]
	,[DWValidToDate]
	,[DWCreatedDate]
	,[DWModifiedDate]
	,[DWIsDeletedInSource]
	,[DWDeletedInSourceDate]
FROM [sourceNuuDataCubusMasterData].[CubusMasterData_DimEmployee_History]
WHERE DWIsCurrent = 1