CREATE TABLE [sourceDataLakeNetcracker_interim].[acchasonetimecharge] (
    [account_num]                    NVARCHAR (500) NULL,
    [otc_seq]                        INT            NULL,
    [otc_dtm]                        NVARCHAR (500) NULL,
    [otc_id]                         INT            NULL,
    [otc_status]                     INT            NULL,
    [otc_mny]                        BIGINT         NULL,
    [cps_id]                         INT            NULL,
    [created_dtm]                    NVARCHAR (500) NULL,
    [geneva_user_ora]                NVARCHAR (500) NULL,
    [realtime_charge_boo]            NVARCHAR (500) NULL,
    [revenue_code_id]                INT            NULL,
    [receivable_class_id]            INT            NULL,
    [otc_class]                      INT            NULL,
    [domain_id]                      INT            NULL,
    [otc_label]                      NVARCHAR (500) NULL,
    [service_address_seq]            INT            NULL,
    [product_seq]                    INT            NULL,
    [budget_centre_seq]              INT            NULL,
    [bill_seq]                       INT            NULL,
    [rev_recognition_class_id]       INT            NULL,
    [otc_txt]                        NVARCHAR (500) NULL,
    [cancelled_txt]                  NVARCHAR (500) NULL,
    [originating_bill_seq]           INT            NULL,
    [originating_bill_version]       INT            NULL,
    [otc_installment_seq]            INT            NULL,
    [installment_number]             INT            NULL,
    [termination_dtm]                NVARCHAR (500) NULL,
    [product_quantity]               INT            NULL,
    [previous_otc_mny]               BIGINT         NULL,
    [revenue_start_dat]              NVARCHAR (500) NULL,
    [revenue_end_dat]                NVARCHAR (500) NULL,
    [upre_seq]                       INT            NULL,
    [random_hash]                    INT            NULL,
    [domain_group_id]                INT            NULL,
    [actual_mny]                     BIGINT         NULL,
    [otc_tax_mny]                    BIGINT         NULL,
    [disc_id_applied_on_otc_create]  NVARCHAR (500) NULL,
    [precalc_disc_amount_on_otc]     BIGINT         NULL,
    [discounted_otc_on_creation_boo] NVARCHAR (500) NULL,
    [alt_currency_code]              NVARCHAR (500) NULL,
    [alt_currency_otc_mny]           BIGINT         NULL,
    [rtpc_otc_lines_tax_mny]         BIGINT         NULL,
    [currency_conversion_ref_dat]    NVARCHAR (500) NULL,
    [otc_name]                       NVARCHAR (500) NULL,
    [prepaid_installment_boo]        NVARCHAR (500) NULL,
    [one_off_accrual_points]         INT            NULL,
    [one_off_accrual_point_rate]     INT            NULL,
    [one_off_redemption_points]      INT            NULL,
    [one_off_redemption_point_rate]  INT            NULL,
    [original_otc_instlmnt_seq]      INT            NULL,
    [original_instlmnt_num]          INT            NULL,
    [DWCreatedDate]                  DATETIME       DEFAULT (getdate()) NULL
);


GO
EXECUTE sp_addextendedproperty @name = N'TruncateBeforeDeploy', @value = N'True', @level0type = N'SCHEMA', @level0name = N'sourceDataLakeNetcracker_interim', @level1type = N'TABLE', @level1name = N'acchasonetimecharge';

