CREATE TABLE [sourceDataLakeNetcracker_interim].[billproductcharge] (
    [account_num]                    NVARCHAR (500) NULL,
    [charge_seq]                     INT            NULL,
    [charge_number]                  INT            NULL,
    [domain_id]                      INT            NULL,
    [customer_ref]                   NVARCHAR (500) NULL,
    [product_seq]                    INT            NULL,
    [product_id]                     INT            NULL,
    [charge_start_dat]               NVARCHAR (500) NULL,
    [charge_end_dat]                 NVARCHAR (500) NULL,
    [charge_cost_mny]                BIGINT         NULL,
    [charge_type]                    INT            NULL,
    [charge_sub_type]                INT            NULL,
    [tariff_id]                      INT            NULL,
    [revenue_code_id]                INT            NULL,
    [cps_id]                         INT            NULL,
    [taxcode_id]                     INT            NULL,
    [percentage_pct]                 INT            NULL,
    [product_quantity]               INT            NULL,
    [product_age]                    INT            NULL,
    [bpc_status]                     INT            NULL,
    [created_dtm]                    NVARCHAR (500) NULL,
    [anchor_dat]                     NVARCHAR (500) NULL,
    [tariff_version]                 INT            NULL,
    [receivable_class_id]            INT            NULL,
    [in_advance_boo]                 NVARCHAR (500) NULL,
    [budget_centre_seq]              INT            NULL,
    [package_seq]                    INT            NULL,
    [package_id]                     INT            NULL,
    [product_package_instance]       INT            NULL,
    [parent_product_seq]             INT            NULL,
    [additions_quantity]             INT            NULL,
    [terminations_quantity]          INT            NULL,
    [package_basic_tariff_id]        INT            NULL,
    [package_basic_cost_mny]         BIGINT         NULL,
    [package_disc_rev_code_id]       INT            NULL,
    [pre_override_cost_mny]          BIGINT         NULL,
    [override_rev_code_id]           INT            NULL,
    [early_term_mult_cost_mny]       BIGINT         NULL,
    [early_term_mult_rev_code_id]    INT            NULL,
    [contract_ref]                   NVARCHAR (500) NULL,
    [contract_term]                  INT            NULL,
    [contract_term_units]            NVARCHAR (500) NULL,
    [product_attr_1]                 NVARCHAR (500) NULL,
    [product_attr_2]                 NVARCHAR (500) NULL,
    [product_attr_3]                 NVARCHAR (500) NULL,
    [product_attr_4]                 NVARCHAR (500) NULL,
    [product_attr_5]                 NVARCHAR (500) NULL,
    [product_attr_6]                 NVARCHAR (500) NULL,
    [override_number]                BIGINT         NULL,
    [override_mod_type_id]           INT            NULL,
    [age_dependent_price_id]         INT            NULL,
    [adp_from_number]                INT            NULL,
    [adp_to_number]                  INT            NULL,
    [adp_period_units]               NVARCHAR (500) NULL,
    [pre_adp_cost_mny]               BIGINT         NULL,
    [adp_recur_disc_rev_code_id]     INT            NULL,
    [full_period_cost_mny]           BIGINT         NULL,
    [charge_start_dtm]               NVARCHAR (500) NULL,
    [charge_end_dtm]                 NVARCHAR (500) NULL,
    [activation_rule]                INT            NULL,
    [suspension_rule]                INT            NULL,
    [reactivation_rule]              INT            NULL,
    [termination_rule]               INT            NULL,
    [rev_recognition_class_id]       INT            NULL,
    [charge_source]                  INT            NULL,
    [contract_start_dat]             NVARCHAR (500) NULL,
    [contract_type_id]               INT            NULL,
    [tax_rate_pct]                   INT            NULL,
    [tax_rate_mny]                   BIGINT         NULL,
    [tax_rate_currency_code]         NVARCHAR (500) NULL,
    [cog_member_qty]                 INT            NULL,
    [accumulated_points]             BIGINT         NULL,
    [redeemed_points]                BIGINT         NULL,
    [pre_loyalty_cost_mny]           BIGINT         NULL,
    [price_attr_1]                   NVARCHAR (500) NULL,
    [price_attr_2]                   NVARCHAR (500) NULL,
    [price_attr_3]                   NVARCHAR (500) NULL,
    [price_attr_4]                   NVARCHAR (500) NULL,
    [price_attr_5]                   NVARCHAR (500) NULL,
    [price_attr_6]                   NVARCHAR (500) NULL,
    [split_charge_amount_mny]        BIGINT         NULL,
    [pre_split_full_period_cost_mny] BIGINT         NULL,
    [split_charge_source]            INT            NULL,
    [actual_charge_start_dat]        NVARCHAR (500) NULL,
    [actual_charge_end_dat]          NVARCHAR (500) NULL,
    [split_amount_overruled_boo]     NVARCHAR (500) NULL,
    [full_period_boo]                NVARCHAR (500) NULL,
    [DWCreatedDate]                  DATETIME       DEFAULT (getdate()) NULL
);


GO
EXECUTE sp_addextendedproperty @name = N'TruncateBeforeDeploy', @value = N'True', @level0type = N'SCHEMA', @level0name = N'sourceDataLakeNetcracker_interim', @level1type = N'TABLE', @level1name = N'billproductcharge';

