

CREATE FUNCTION [meta].[SplitCamelCase](@X VARCHAR(8000))
RETURNS VARCHAR(8000) AS
BEGIN
WHILE PATINDEX('%[^ ][ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
COLLATE SQL_Latin1_General_CP1_CS_AS,
@X COLLATE SQL_Latin1_General_CP1_CS_AS) > 0
SET @X = STUFF(@X,
PATINDEX('%[^ ][ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
COLLATE SQL_Latin1_General_CP1_CS_AS,
@X COLLATE SQL_Latin1_General_CP1_CS_AS) + 1, 0, ' ')
RETURN @X
END