
CREATE VIEW [factView].[ProductSubscriptions] 
AS
SELECT
	[CalendarFromID]
	,[CalendarToID]
	,[SubscriptionID]
	,[ProductID]
	,[CustomerID]
	,[SalesChannelID]
	,[AddressBillingID]
	,[BillingAccountID]
	,[PhoneDetailID]
	,[TechnologyID]
	,[EmployeeID]
	,[QuoteID]
	,[QuoteItemID]
	,[CalendarPlannedID]
	,[CalendarActivatedID]
	,[CalendarCancelledID]
	,[CalendarDisconnectedPlannedID]
	,[CalendarDisconnectedExpectedID]
	,[CalendarDisconnectedCancelledID]
	,[CalendarDisconnectedID]
	,[CalendarRGUFromID]
	,[CalendarRGUToID]
	,[CalendarMigrationLegacyID]
	,[DWCreatedDate]
	,[DWModifiedDate]
	
FROM [fact].[ProductSubscriptions]