CREATE VIEW [factView].[ProductTransactions] 
AS
SELECT
	[CalendarID]
	,[TimeID]
	,[ProductID]
	,[CustomerID]
	,[AddressBillingID]
	,[HouseHoldID]
	,[SalesChannelID]
	,[TransactionStateID]
	,[ProductTransactionsQuantity]
	,[ProductChurnQuantity]
	,[CalendarToID]
	,[TimeToID]
	,[CalendarCommitmentToID]
	,[TimeCommitmentToID]
	,[PhoneDetailID]
	,[TLO]
	,[ProductParentID]
	,[RGU]
	,[Migration]
	,[ProductUpgrade]
	,[DWCreatedDate]
	,[DWModifiedDate]
	
FROM [fact].[ProductTransactions]