CREATE TABLE [sourceNuudlNetCracker].[cpmnrmltroubleticket] (
    [approval_reason]                                                    NVARCHAR (300) NULL,
    [closed_by_date]                                                     DATETIME2 (7)  NULL,
    [closed_by_user_id]                                                  NVARCHAR (36)  NULL,
    [closed_by_user_name]                                                NVARCHAR (300) NULL,
    [created_by_date]                                                    DATETIME2 (7)  NULL,
    [created_by_user_id]                                                 NVARCHAR (36)  NULL,
    [created_by_user_name]                                               NVARCHAR (300) NULL,
    [description]                                                        NVARCHAR (300) NULL,
    [first_resolution_date]                                              DATETIME2 (7)  NULL,
    [is_solution_visible_for_contact]                                    BIT            NULL,
    [last_approved_by_date]                                              DATETIME2 (7)  NULL,
    [last_approved_by_user_id]                                           NVARCHAR (36)  NULL,
    [last_approved_by_user_name]                                         NVARCHAR (300) NULL,
    [last_updated_by_date]                                               DATETIME2 (7)  NULL,
    [last_updated_by_user_id]                                            NVARCHAR (36)  NULL,
    [last_updated_by_user_name]                                          NVARCHAR (300) NULL,
    [problem_start_date]                                                 DATETIME2 (7)  NULL,
    [resolution_reason]                                                  NVARCHAR (300) NULL,
    [resolved_by_date]                                                   DATETIME2 (7)  NULL,
    [resolved_by_user_id]                                                NVARCHAR (36)  NULL,
    [resolved_by_user_name]                                              NVARCHAR (300) NULL,
    [solution]                                                           NVARCHAR (300) NULL,
    [ticket_category]                                                    NVARCHAR (300) NULL,
    [version]                                                            DECIMAL (10)   NULL,
    [channel_id]                                                         NVARCHAR (36)  NULL,
    [expected_resolution_date]                                           DATETIME2 (7)  NULL,
    [external_id]                                                        NVARCHAR (36)  NULL,
    [priority]                                                           NVARCHAR (300) NULL,
    [requested_resolution_date]                                          DATETIME2 (7)  NULL,
    [severity]                                                           NVARCHAR (300) NULL,
    [status]                                                             NVARCHAR (300) NULL,
    [status_change_date]                                                 DATETIME2 (7)  NULL,
    [status_change_reason]                                               NVARCHAR (300) NULL,
    [ticket_type]                                                        NVARCHAR (300) NULL,
    [id]                                                                 NVARCHAR (36)  NULL,
    [name]                                                               NVARCHAR (300) NULL,
    [group_assignee_id]                                                  NVARCHAR (36)  NULL,
    [group_assignee_name]                                                NVARCHAR (300) NULL,
    [user_assignee_id]                                                   NVARCHAR (36)  NULL,
    [user_assignee_name]                                                 NVARCHAR (300) NULL,
    [reporter_id]                                                        NVARCHAR (36)  NULL,
    [reporter_name]                                                      NVARCHAR (300) NULL,
    [project_id]                                                         NVARCHAR (36)  NULL,
    [project_name]                                                       NVARCHAR (300) NULL,
    [group_assignee_type]                                                NVARCHAR (300) NULL,
    [reporter_type]                                                      NVARCHAR (300) NULL,
    [user_assignee_type]                                                 NVARCHAR (300) NULL,
    [closure_code]                                                       NVARCHAR (300) NULL,
    [is_deleted]                                                         BIT            NULL,
    [last_modified_ts]                                                   DATETIME2 (7)  NULL,
    [extended_attributes_json_DPT_RETRY]                                 NVARCHAR (300) NULL,
    [extended_attributes_json__corrupt_record]                           NVARCHAR (300) NULL,
    [extended_attributes_json_accountNumber]                             NVARCHAR (300) NULL,
    [extended_attributes_json_billId]                                    NVARCHAR (36)  NULL,
    [extended_attributes_json_changeDate]                                NVARCHAR (300) NULL,
    [extended_attributes_json_change_id]                                 NVARCHAR (36)  NULL,
    [extended_attributes_json_commitmentFee]                             NVARCHAR (300) NULL,
    [extended_attributes_json_cpmChannel]                                NVARCHAR (300) NULL,
    [extended_attributes_json_deviceModel]                               NVARCHAR (300) NULL,
    [extended_attributes_json_distributionChannel]                       NVARCHAR (300) NULL,
    [extended_attributes_json_earlyTerminationFee]                       NVARCHAR (300) NULL,
    [extended_attributes_json_ichOrderId]                                NVARCHAR (36)  NULL,
    [extended_attributes_json_imei]                                      NVARCHAR (300) NULL,
    [extended_attributes_json_internationalPhoneNumber]                  NVARCHAR (300) NULL,
    [extended_attributes_json_lastExecutedStep]                          NVARCHAR (300) NULL,
    [extended_attributes_json_legacyReturnOption]                        NVARCHAR (300) NULL,
    [extended_attributes_json_noInWarehouse]                             NVARCHAR (300) NULL,
    [extended_attributes_json_parentTicketCategory]                      NVARCHAR (300) NULL,
    [extended_attributes_json_portedTo]                                  NVARCHAR (300) NULL,
    [extended_attributes_json_purchaseDate]                              NVARCHAR (300) NULL,
    [extended_attributes_json_reason]                                    NVARCHAR (300) NULL,
    [extended_attributes_json_receiptNumber]                             NVARCHAR (300) NULL,
    [extended_attributes_json_refundAmount]                              NVARCHAR (300) NULL,
    [extended_attributes_json_refundOption]                              NVARCHAR (300) NULL,
    [extended_attributes_json_registrationNumber]                        NVARCHAR (300) NULL,
    [extended_attributes_json_returnBy]                                  NVARCHAR (300) NULL,
    [extended_attributes_json_returnMethod]                              NVARCHAR (300) NULL,
    [extended_attributes_json_rphRefundLink]                             NVARCHAR (300) NULL,
    [extended_attributes_json_serialNumber]                              NVARCHAR (300) NULL,
    [extended_attributes_json_storeId]                                   BIGINT         NULL,
    [extended_attributes_json_trackingNumber]                            NVARCHAR (300) NULL,
    [tags_json__corrupt_record]                                          NVARCHAR (300) NULL,
    [total_disputed_amount_json__corrupt_record]                         NVARCHAR (300) NULL,
    [total_disputed_amount_json_amount]                                  BIGINT         NULL,
    [total_disputed_amount_json_currencyCode]                            NVARCHAR (300) NULL,
    [total_disputed_amount_json_exponent]                                BIGINT         NULL,
    [total_initial_amount_json__corrupt_record]                          NVARCHAR (300) NULL,
    [total_initial_amount_json_amount]                                   BIGINT         NULL,
    [total_initial_amount_json_currencyCode]                             NVARCHAR (300) NULL,
    [total_initial_amount_json_exponent]                                 BIGINT         NULL,
    [extended_attributes_json_refundParameters_json_POSPaymentBreakdown] NVARCHAR (300) NULL,
    [extended_attributes_json_refundParameters_json_billingAccountId]    NVARCHAR (36)  NULL,
    [extended_attributes_json_refundParameters_json_paymentId]           NVARCHAR (36)  NULL,
    [extended_attributes_json_refundParameters_json_paymentProvider]     NVARCHAR (300) NULL,
    [extended_attributes_json_refundParameters_json_refundId]            NVARCHAR (36)  NULL,
    [extended_attributes_json_refundParameters_json_refundPaymentId]     NVARCHAR (36)  NULL,
    [extended_attributes_json_rentedEquipmentToReturn_json_id]           NVARCHAR (36)  NULL,
    [extended_attributes_json_rentedEquipmentToReturn_json_name]         NVARCHAR (300) NULL,
    [extended_attributes_json_rentedEquipmentToReturn_json_returnOption] NVARCHAR (300) NULL,
    [NUUDL_ValidFrom]                                                    DATETIME2 (7)  NULL,
    [NUUDL_ValidTo]                                                      DATETIME2 (7)  NULL,
    [NUUDL_IsCurrent]                                                    BIT            NULL,
    [NUUDL_ID]                                                           BIGINT         NOT NULL,
    [NUUDL_StandardizedProcessedTimestamp]                               DATETIME2 (7)  NULL,
    [NUUDL_CuratedBatchID]                                               INT            NULL,
    [NUUDL_CuratedProcessedTimestamp]                                    NVARCHAR (300) NULL,
    [NUUDL_CuratedSourceFilename]                                        NVARCHAR (300) NULL,
    [DWCreatedDate]                                                      DATETIME2 (7)  DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_cpmnrmltroubleticket] PRIMARY KEY NONCLUSTERED ([NUUDL_ID] ASC)
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_cpmnrmltroubleticket]
    ON [sourceNuudlNetCracker].[cpmnrmltroubleticket];

