CREATE TABLE [sourceNuudlNetCracker].[ibsitemshistory_History] (
    [id]                                                                     NVARCHAR (36)  NULL,
    [version]                                                                BIGINT         NULL,
    [schema_version]                                                         NVARCHAR (300) NULL,
    [active_from]                                                            DATETIME2 (7)  NULL,
    [active_to]                                                              DATETIME2 (7)  NULL,
    [is_snapshot]                                                            BIT            NULL,
    [state]                                                                  NVARCHAR (300) NULL,
    [idempotency_key]                                                        NVARCHAR (300) NULL,
    [is_deleted]                                                             BIT            NULL,
    [last_modified_ts]                                                       DATETIME2 (7)  NULL,
    [is_current]                                                             BIT            NULL,
    [item_json_appliedBusinessBarringId]                                     NVARCHAR (36)  NULL,
    [item_json_appliedByBusinessRuleId]                                      NVARCHAR (36)  NULL,
    [NUUDL_ValidTo]                                                          DATETIME2 (7)  NULL,
    [NUUDL_ValidFrom]                                                        DATETIME2 (7)  NULL,
    [NUUDL_IsCurrent]                                                        BIT            NULL,
    [item_json_creationDate]                                                 NVARCHAR (300) NULL,
    [item_json_customerCategoryId]                                           NVARCHAR (36)  NULL,
    [item_json_customerId]                                                   NVARCHAR (36)  NULL,
    [item_json_disconnectionReason]                                          NVARCHAR (300) NULL,
    [item_json_disconnectionReasonDescription]                               NVARCHAR (800) NULL,
    [item_json_distributionChannelId]                                        NVARCHAR (36)  NULL,
    [item_json_effectiveDate]                                                NVARCHAR (300) NULL,
    [item_json_expirationDate]                                               NVARCHAR (300) NULL,
    [item_json_id]                                                           NVARCHAR (36)  NULL,
    [item_json_marketId]                                                     NVARCHAR (36)  NULL,
    [item_json_marketingBundleComponentId]                                   NVARCHAR (36)  NULL,
    [item_json_name]                                                         NVARCHAR (300) NULL,
    [item_json_offeringId]                                                   NVARCHAR (36)  NULL,
    [item_json_offeringName]                                                 NVARCHAR (300) NULL,
    [item_json_originalExpirationDate]                                       NVARCHAR (300) NULL,
    [item_json_overrideMode]                                                 NVARCHAR (300) NULL,
    [item_json_parentId]                                                     NVARCHAR (36)  NULL,
    [item_json_previousBusinessGroupId]                                      NVARCHAR (36)  NULL,
    [item_json_productFamilyId]                                              NVARCHAR (36)  NULL,
    [item_json_productFamilyName]                                            NVARCHAR (300) NULL,
    [item_json_productOrderId]                                               NVARCHAR (36)  NULL,
    [item_json_prohibitManualRemoval]                                        BIT            NULL,
    [item_json_quoteId]                                                      NVARCHAR (36)  NULL,
    [item_json_rootId]                                                       NVARCHAR (36)  NULL,
    [item_json_startDate]                                                    NVARCHAR (300) NULL,
    [item_json_state]                                                        NVARCHAR (300) NULL,
    [item_json_suspended]                                                    BIT            NULL,
    [item_json_terminationDate]                                              NVARCHAR (300) NULL,
    [item_json_type]                                                         NVARCHAR (300) NULL,
    [item_json_accountRef_json_name]                                         NVARCHAR (300) NULL,
    [item_json_accountRef_json_refId]                                        NVARCHAR (36)  NULL,
    [item_json_accountRef_json_refType]                                      NVARCHAR (300) NULL,
    [item_json_agreementRef_json_agreementType]                              NVARCHAR (300) NULL,
    [item_json_agreementRef_json_name]                                       NVARCHAR (300) NULL,
    [item_json_agreementRef_json_refId]                                      NVARCHAR (36)  NULL,
    [item_json_businessBarringRecords_json_businessBarringSpecificationId]   NVARCHAR (36)  NULL,
    [item_json_businessBarringRecords_json_id]                               NVARCHAR (36)  NULL,
    [item_json_businessBarringRecords_json_name]                             NVARCHAR (300) NULL,
    [item_json_businessBarringRecords_json_validFrom]                        NVARCHAR (300) NULL,
    [item_json_businessBarringRecords_json_validTo]                          NVARCHAR (300) NULL,
    [item_json_businessGroup_json_id]                                        NVARCHAR (36)  NULL,
    [item_json_businessGroup_json_marketingBundleId]                         NVARCHAR (36)  NULL,
    [item_json_businessGroup_json_name]                                      NVARCHAR (300) NULL,
    [item_json_businessGroup_json_type]                                      NVARCHAR (300) NULL,
    [item_json_characteristics_json_attributeId]                             NVARCHAR (36)  NULL,
    [item_json_characteristics_json_name]                                    NVARCHAR (300) NULL,
    [item_json_characteristics_json_offeringCharId]                          NVARCHAR (36)  NULL,
    [item_json_characteristics_json_productSpecCharId]                       NVARCHAR (36)  NULL,
    [item_json_characteristics_json_value]                                   NVARCHAR (300) NULL,
    [item_json_extendedAttributes_json_key]                                  NVARCHAR (300) NULL,
    [item_json_extendedAttributes_json_value]                                NVARCHAR (800) NULL,
    [item_json_prices_json_id]                                               NVARCHAR (36)  NULL,
    [item_json_prices_json_type]                                             NVARCHAR (300) NULL,
    [item_json_prices_json_validFrom]                                        NVARCHAR (300) NULL,
    [item_json_prices_json_validTo]                                          NVARCHAR (300) NULL,
    [item_json_productSpecificationRef_json_id]                              NVARCHAR (36)  NULL,
    [item_json_productSpecificationRef_json_name]                            NVARCHAR (300) NULL,
    [item_json_productSpecificationRef_json_version]                         NVARCHAR (300) NULL,
    [item_json_realizingServiceRefs_json_id]                                 NVARCHAR (36)  NULL,
    [item_json_realizingServiceRefs_json_name]                               NVARCHAR (300) NULL,
    [item_json_realizingServiceRefs_json_refId]                              NVARCHAR (36)  NULL,
    [item_json_realizingServiceRefs_json_role]                               NVARCHAR (300) NULL,
    [item_json_relatedPartyRef_json_name]                                    NVARCHAR (300) NULL,
    [item_json_relatedPartyRef_json_refId]                                   NVARCHAR (36)  NULL,
    [item_json_relatedPartyRef_json_referredType]                            NVARCHAR (300) NULL,
    [item_json_relatedPartyRef_json_role]                                    NVARCHAR (300) NULL,
    [item_json_relatedPartyRef_json_userOfService]                           BIT            NULL,
    [item_json_technicalBarringRecords_json_barringType]                     NVARCHAR (300) NULL,
    [item_json_technicalBarringRecords_json_businessBarringRecordId]         NVARCHAR (36)  NULL,
    [item_json_technicalBarringRecords_json_id]                              NVARCHAR (36)  NULL,
    [item_json_technicalBarringRecords_json_technicalBarringSpecificationId] NVARCHAR (36)  NULL,
    [item_json_technicalBarringRecords_json_validFrom]                       NVARCHAR (300) NULL,
    [item_json_technicalBarringRecords_json_validTo]                         NVARCHAR (300) NULL,
    [item_json_prices_json_alterationPrices_json_alterationOnSuspendedPrice] BIT            NULL,
    [item_json_prices_json_alterationPrices_json_discountId]                 NVARCHAR (36)  NULL,
    [item_json_prices_json_alterationPrices_json_id]                         NVARCHAR (36)  NULL,
    [item_json_prices_json_alterationPrices_json_priceAlterationType]        NVARCHAR (300) NULL,
    [item_json_prices_json_alterationPrices_json_reason]                     NVARCHAR (300) NULL,
    [item_json_prices_json_alterationPrices_json_state]                      NVARCHAR (300) NULL,
    [item_json_prices_json_alterationPrices_json_ticketId]                   NVARCHAR (36)  NULL,
    [item_json_prices_json_alterationPrices_json_type]                       NVARCHAR (300) NULL,
    [item_json_prices_json_alterationPrices_json_validFrom]                  NVARCHAR (300) NULL,
    [item_json_prices_json_alterationPrices_json_validTo]                    NVARCHAR (300) NULL,
    [NUUDL_ID]                                                               BIGINT         NOT NULL,
    [NUUDL_CuratedBatchID]                                                   BIGINT         NULL,
    [DWIsCurrent]                                                            BIT            NULL,
    [DWValidFromDate]                                                        DATETIME2 (7)  NOT NULL,
    [DWValidToDate]                                                          DATETIME2 (7)  NULL,
    [DWCreatedDate]                                                          DATETIME2 (7)  NULL,
    [DWModifiedDate]                                                         DATETIME2 (7)  NULL,
    [DWIsDeletedInSource]                                                    BIT            NULL,
    [DWDeletedInSourceDate]                                                  DATETIME2 (7)  NULL,
    CONSTRAINT [PK_ibsitemshistory_History] PRIMARY KEY NONCLUSTERED ([NUUDL_ID] ASC, [DWValidFromDate] ASC)
);




GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_ibsitemshistory_History]
    ON [sourceNuudlNetCracker].[ibsitemshistory_History];


GO
CREATE NONCLUSTERED INDEX [NCIX_ibsitemshistory_History__DWIsCurrent_id]
    ON [sourceNuudlNetCracker].[ibsitemshistory_History]([DWIsCurrent] ASC, [id] ASC)
    INCLUDE([item_json_parentId], [item_json_offeringId], [item_json_offeringName], [item_json_rootId], [item_json_distributionChannelId], [item_json_customerId], [item_json_expirationDate], [item_json_quoteId], [item_json_accountRef_json_refId], [item_json_characteristics_json_name], [state], [active_from]);

