CREATE TABLE [sourceNuudlNetCracker].[ibsnrmlproductinstance_History] (
    [account_ref_id]                           NVARCHAR (36)    NULL,
    [business_group]                           NVARCHAR (300)   NULL,
    [contracted_date]                          DATETIME2 (7)    NULL,
    [customer_id]                              NVARCHAR (36)    NULL,
    [description]                              NVARCHAR (300)   NULL,
    [disconnection_reason]                     NVARCHAR (300)   NULL,
    [disconnection_reason_description]         NVARCHAR (300)   NULL,
    [effective_date]                           DATETIME2 (7)    NULL,
    [eligibility_param_id]                     NVARCHAR (36)    NULL,
    [extended_attributes_json__corrupt_record] NVARCHAR (4000)  NULL,
    [extended_eligibility]                     NVARCHAR (300)   NULL,
    [external_id]                              NVARCHAR (36)    NULL,
    [id]                                       NVARCHAR (36)    NULL,
    [idempotency_key]                          NVARCHAR (300)   NULL,
    [last_modified]                            DATETIME2 (7)    NULL,
    [expiration_date]                          DATETIME2 (7)    NULL,
    [name]                                     NVARCHAR (300)   NULL,
    [number_of_installments]                   INT              NULL,
    [offering_id]                              NVARCHAR (36)    NULL,
    [override_mode]                            NVARCHAR (300)   NULL,
    [parent_id]                                NVARCHAR (36)    NULL,
    [place_ref_id]                             NVARCHAR (36)    NULL,
    [product_order_id]                         NVARCHAR (36)    NULL,
    [product_specification_id]                 NVARCHAR (36)    NULL,
    [product_specification_version]            DECIMAL (36, 12) NULL,
    [quantity]                                 INT              NULL,
    [quote_id]                                 NVARCHAR (36)    NULL,
    [root_id]                                  NVARCHAR (36)    NULL,
    [source_quote_item_id]                     NVARCHAR (36)    NULL,
    [start_date]                               DATETIME2 (7)    NULL,
    [state]                                    NVARCHAR (300)   NULL,
    [suspended]                                BIT              NULL,
    [termination_date]                         DATETIME2 (7)    NULL,
    [type]                                     NVARCHAR (300)   NULL,
    [version]                                  INT              NULL,
    [is_deleted]                               BIT              NULL,
    [last_modified_ts]                         DATETIME2 (7)    NULL,
    [is_current]                               BIT              NULL,
    [extended_attributes_json_key]             NVARCHAR (4000)  NULL,
    [extended_attributes_json_value]           NVARCHAR (4000)  NULL,
    [NUUDL_ValidFrom]                          DATETIME2 (7)    NULL,
    [NUUDL_ValidTo]                            DATETIME2 (7)    NULL,
    [NUUDL_IsCurrent]                          BIT              NULL,
    [NUUDL_ID]                                 BIGINT           NOT NULL,
    [NUUDL_CuratedBatchID]                     BIGINT           NULL,
    [DWIsCurrent]                              BIT              NULL,
    [DWValidFromDate]                          DATETIME2 (7)    NOT NULL,
    [DWValidToDate]                            DATETIME2 (7)    NULL,
    [DWCreatedDate]                            DATETIME2 (7)    NULL,
    [DWModifiedDate]                           DATETIME2 (7)    NULL,
    [DWIsDeletedInSource]                      BIT              NULL,
    [DWDeletedInSourceDate]                    DATETIME2 (7)    NULL,
    CONSTRAINT [PK_ibsnrmlproductinstance_History] PRIMARY KEY NONCLUSTERED ([NUUDL_ID] ASC, [DWValidFromDate] ASC)
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_ibsnrmlproductinstance_History]
    ON [sourceNuudlNetCracker].[ibsnrmlproductinstance_History];

