CREATE TABLE [sourceNuudlNetCracker].[qssnrmlquoteitem_History] (
    [account_id]                                                        NVARCHAR (36)   NULL,
    [action]                                                            NVARCHAR (300)  NULL,
    [active_from]                                                       DATETIME2 (7)   NULL,
    [active_to]                                                         NVARCHAR (300)  NULL,
    [amount]                                                            NVARCHAR (300)  NULL,
    [approval_level]                                                    NVARCHAR (300)  NULL,
    [availability_check_result]                                         NVARCHAR (300)  NULL,
    [business_action]                                                   NVARCHAR (300)  NULL,
    [business_group_id]                                                 NVARCHAR (36)   NULL,
    [business_group_name]                                               NVARCHAR (300)  NULL,
    [contracted_date]                                                   NVARCHAR (300)  NULL,
    [creation_time]                                                     DATETIME2 (7)   NULL,
    [disconnection_reason]                                              NVARCHAR (300)  NULL,
    [distribution_channel_id]                                           NVARCHAR (36)   NULL,
    [extended_parameters_json_0000372d_163b_48c9_83a9_17d7a237a2c0]     NVARCHAR (4000) NULL,
    [extended_parameters_json_150338a0_0cf7_4428_b3fc_dbca99bd9343]     NVARCHAR (4000) NULL,
    [extended_parameters_json_2262debf_d95a_4e8b_957a_a3908b7c5df9]     NVARCHAR (4000) NULL,
    [extended_parameters_json_2ee0ab36_03de_4020_a9c8_0793209a7ac7]     NVARCHAR (4000) NULL,
    [extended_parameters_json_465526c0_80c5_4a06_89ed_3a3bd6957c83]     NVARCHAR (4000) NULL,
    [extended_parameters_json_4a15af47_9eb0_4546_8c9c_bc75387fe74c]     NVARCHAR (4000) NULL,
    [extended_parameters_json_55ab2bdf_151f_4c38_937f_7b5d337e6756]     NVARCHAR (4000) NULL,
    [extended_parameters_json_6409d551_fcfe_4dc2_a552_776e73bb3f69]     NVARCHAR (4000) NULL,
    [extended_parameters_json_7c4b0eb2_5c5a_40da_8e12_0a0718273e3b]     NVARCHAR (4000) NULL,
    [extended_parameters_json_activationDateOnWorkingDay]               NVARCHAR (4000) NULL,
    [extended_parameters_json_af199492_152e_459c_a32b_eef81eef0a71]     NVARCHAR (4000) NULL,
    [extended_parameters_json_agreementId]                              NVARCHAR (4000) NULL,
    [extended_parameters_json_availabilityDate]                         NVARCHAR (4000) NULL,
    [extended_parameters_json_d22ac111_fb6a_42ba_b1b3_23b32b923d73]     NVARCHAR (4000) NULL,
    [extended_parameters_json_deactivationFee]                          NVARCHAR (4000) NULL,
    [extended_parameters_json_deviceReturnOperation]                    NVARCHAR (4000) NULL,
    [extended_parameters_json_df9bf9ab_7965_4cf2_8c5d_32d8c2e97e93]     NVARCHAR (4000) NULL,
    [extended_parameters_json_e012d094_2cbf_46cc_82e5_a915f9751e09]     NVARCHAR (4000) NULL,
    [extended_parameters_json_extPaymentId]                             NVARCHAR (4000) NULL,
    [extended_parameters_json_f025e2e4_041c_43e9_875b_21309590e15c]     NVARCHAR (4000) NULL,
    [extended_parameters_json_feePerDay]                                NVARCHAR (4000) NULL,
    [extended_parameters_json_ff18f216_93ee_486d_86eb_b0d8396ce420]     NVARCHAR (4000) NULL,
    [extended_parameters_json_isInsuranceAdded]                         NVARCHAR (4000) NULL,
    [extended_parameters_json_isPoaSigned]                              NVARCHAR (4000) NULL,
    [extended_parameters_json_noInWarehouse]                            NVARCHAR (4000) NULL,
    [extended_parameters_json_offeringBusinessUse]                      NVARCHAR (4000) NULL,
    [extended_parameters_json_paymentProvider]                          NVARCHAR (4000) NULL,
    [extended_parameters_json_portalActivationDateIsNotProvided]        NVARCHAR (4000) NULL,
    [extended_parameters_json_portalEndOfTheNoticePeriodOptionSelected] NVARCHAR (4000) NULL,
    [extended_parameters_json_portalRefuseUsageSpendLimit]              NVARCHAR (4000) NULL,
    [extended_parameters_json_portInTermsAccepted]                      NVARCHAR (4000) NULL,
    [extended_parameters_json_preOrder]                                 NVARCHAR (4000) NULL,
    [extended_parameters_json_returnMethod]                             NVARCHAR (4000) NULL,
    [extended_parameters_json_softReservationState]                     NVARCHAR (4000) NULL,
    [extended_parameters_json_undefined]                                NVARCHAR (4000) NULL,
    [extended_parameters_json_userEmail]                                NVARCHAR (4000) NULL,
    [extended_parameters_json_userName]                                 NVARCHAR (4000) NULL,
    [extended_parameters_json_userPhone]                                NVARCHAR (4000) NULL,
    [geo_site_id]                                                       NVARCHAR (36)   NULL,
    [id]                                                                NVARCHAR (36)   NULL,
    [market_id]                                                         NVARCHAR (36)   NULL,
    [marketing_bundle_id]                                               NVARCHAR (36)   NULL,
    [number_of_installments]                                            NVARCHAR (300)  NULL,
    [parent_quote_item_id]                                              NVARCHAR (36)   NULL,
    [planned_disconnection_date]                                        NVARCHAR (300)  NULL,
    [product_instance_id]                                               NVARCHAR (36)   NULL,
    [product_offering_id]                                               NVARCHAR (36)   NULL,
    [product_specification_id]                                          NVARCHAR (36)   NULL,
    [product_specification_version]                                     NVARCHAR (300)  NULL,
    [quantity]                                                          INT             NULL,
    [quote_id]                                                          NVARCHAR (36)   NULL,
    [root_quote_item_id]                                                NVARCHAR (36)   NULL,
    [state]                                                             NVARCHAR (300)  NULL,
    [quote_version]                                                     NVARCHAR (300)  NULL,
    [is_deleted]                                                        BIT             NULL,
    [last_modified_ts]                                                  DATETIME2 (7)   NULL,
    [is_current]                                                        BIT             NULL,
    [NUUDL_ValidFrom]                                                   DATETIME2 (7)   NULL,
    [NUUDL_ValidTo]                                                     DATETIME2 (7)   NULL,
    [NUUDL_IsCurrent]                                                   BIT             NULL,
    [NUUDL_ID]                                                          BIGINT          NOT NULL,
    [NUUDL_CuratedBatchID]                                              BIGINT          NULL,
    [DWIsCurrent]                                                       BIT             NULL,
    [DWValidFromDate]                                                   DATETIME2 (7)   NOT NULL,
    [DWValidToDate]                                                     DATETIME2 (7)   NULL,
    [DWCreatedDate]                                                     DATETIME2 (7)   NULL,
    [DWModifiedDate]                                                    DATETIME2 (7)   NULL,
    [DWIsDeletedInSource]                                               BIT             NULL,
    [DWDeletedInSourceDate]                                             DATETIME2 (7)   NULL,
    CONSTRAINT [PK_qssnrmlquoteitem_History] PRIMARY KEY NONCLUSTERED ([NUUDL_ID] ASC, [DWValidFromDate] ASC)
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_qssnrmlquoteitem_History]
    ON [sourceNuudlNetCracker].[qssnrmlquoteitem_History];

