CREATE TABLE [sourceNuudlNetCracker].[qssnrmlquote_History] (
    [approval_level]                                                NVARCHAR (300)  NULL,
    [assign_to]                                                     NVARCHAR (300)  NULL,
    [brand_id]                                                      NVARCHAR (36)   NULL,
    [business_action]                                               NVARCHAR (300)  NULL,
    [cancellation_reason]                                           NVARCHAR (300)  NULL,
    [customer_category_id]                                          NVARCHAR (36)   NULL,
    [customer_committed_date]                                       NVARCHAR (300)  NULL,
    [customer_id]                                                   NVARCHAR (36)   NULL,
    [customer_requested_date]                                       NVARCHAR (300)  NULL,
    [delivery_method]                                               NVARCHAR (300)  NULL,
    [distribution_channel_id]                                       NVARCHAR (36)   NULL,
    [expiration_date]                                               DATETIME2 (7)   NULL,
    [extended_parameters_json_activityTime]                         NVARCHAR (4000) NULL,
    [extended_parameters_json_agreementId]                          NVARCHAR (4000) NULL,
    [extended_parameters_json_ApplicationGuid]                      NVARCHAR (4000) NULL,
    [extended_parameters_json_authDateTime]                         NVARCHAR (4000) NULL,
    [extended_parameters_json_autoPaymentFlag]                      NVARCHAR (4000) NULL,
    [extended_parameters_json_cardExpiryDate]                       NVARCHAR (4000) NULL,
    [extended_parameters_json_cardNumber]                           NVARCHAR (4000) NULL,
    [extended_parameters_json_cardType]                             NVARCHAR (4000) NULL,
    [extended_parameters_json_contactForAbandoned]                  NVARCHAR (4000) NULL,
    [extended_parameters_json_creditCheckDate]                      NVARCHAR (4000) NULL,
    [extended_parameters_json_creditCheckDetails]                   NVARCHAR (4000) NULL,
    [extended_parameters_json_creditCheckExpirationDate]            NVARCHAR (4000) NULL,
    [extended_parameters_json_creditCheckRequired]                  NVARCHAR (4000) NULL,
    [extended_parameters_json_creditCheckStatus]                    NVARCHAR (4000) NULL,
    [extended_parameters_json_currentStockId]                       NVARCHAR (4000) NULL,
    [extended_parameters_json_customerAccountNumber]                NVARCHAR (4000) NULL,
    [extended_parameters_json_customerFirstName]                    NVARCHAR (4000) NULL,
    [extended_parameters_json_disruptionConsent]                    NVARCHAR (4000) NULL,
    [extended_parameters_json_documentLastDigits]                   NVARCHAR (4000) NULL,
    [extended_parameters_json_documentType]                         NVARCHAR (4000) NULL,
    [extended_parameters_json_extPaymentId]                         NVARCHAR (4000) NULL,
    [extended_parameters_json_flow_id]                              NVARCHAR (4000) NULL,
    [extended_parameters_json_flowId]                               NVARCHAR (4000) NULL,
    [extended_parameters_json_formId]                               NVARCHAR (4000) NULL,
    [extended_parameters_json_hardReservationState]                 NVARCHAR (4000) NULL,
    [extended_parameters_json_infoId]                               NVARCHAR (4000) NULL,
    [extended_parameters_json_initialTotalLoanAmount]               NVARCHAR (4000) NULL,
    [extended_parameters_json_isLoanAvailable]                      NVARCHAR (4000) NULL,
    [extended_parameters_json_loanApplicationGuid]                  NVARCHAR (4000) NULL,
    [extended_parameters_json_loanApplicationId]                    NVARCHAR (4000) NULL,
    [extended_parameters_json_loanRequestNotAvailable]              NVARCHAR (4000) NULL,
    [extended_parameters_json_loanRequestStatus]                    NVARCHAR (4000) NULL,
    [extended_parameters_json_loanTerm]                             NVARCHAR (4000) NULL,
    [extended_parameters_json_marketId]                             NVARCHAR (4000) NULL,
    [extended_parameters_json_marketingConsent]                     NVARCHAR (4000) NULL,
    [extended_parameters_json_mobilePhoneNumber]                    NVARCHAR (4000) NULL,
    [extended_parameters_json_mpNumber]                             NVARCHAR (4000) NULL,
    [extended_parameters_json_partnerId]                            NVARCHAR (4000) NULL,
    [extended_parameters_json_PAYMENT_STATUS]                       NVARCHAR (4000) NULL,
    [extended_parameters_json_paymentProvider]                      NVARCHAR (4000) NULL,
    [extended_parameters_json_paymentSubscriptionId]                NVARCHAR (4000) NULL,
    [extended_parameters_json_portalDeliveryIsConfirmed]            NVARCHAR (4000) NULL,
    [extended_parameters_json_portalExpressBankLoanApproved]        NVARCHAR (4000) NULL,
    [extended_parameters_json_portalFinancingOptionsConfirmed]      NVARCHAR (4000) NULL,
    [extended_parameters_json_portalPersonalInformationIsConfirmed] NVARCHAR (4000) NULL,
    [extended_parameters_json_portalQuoteReviewConfirmed]           NVARCHAR (4000) NULL,
    [extended_parameters_json_requestStatus]                        NVARCHAR (4000) NULL,
    [extended_parameters_json_reservationExpirationDate]            NVARCHAR (4000) NULL,
    [extended_parameters_json_stockAddress]                         NVARCHAR (4000) NULL,
    [extended_parameters_json_stockName]                            NVARCHAR (4000) NULL,
    [external_id]                                                   NVARCHAR (36)   NULL,
    [id]                                                            NVARCHAR (36)   NULL,
    [initial_distribution_channel_id]                               NVARCHAR (36)   NULL,
    [name]                                                          NVARCHAR (300)  NULL,
    [new_msa]                                                       BIT             NULL,
    [number]                                                        NVARCHAR (300)  NULL,
    [opportunity_id]                                                NVARCHAR (36)   NULL,
    [override_mode]                                                 NVARCHAR (300)  NULL,
    [owner]                                                         NVARCHAR (300)  NULL,
    [price_list_id]                                                 NVARCHAR (36)   NULL,
    [quote_creation_date]                                           DATETIME2 (7)   NULL,
    [revision]                                                      NVARCHAR (300)  NULL,
    [state]                                                         NVARCHAR (300)  NULL,
    [updated_when]                                                  DATETIME2 (7)   NULL,
    [version]                                                       NVARCHAR (300)  NULL,
    [is_deleted]                                                    BIT             NULL,
    [last_modified_ts]                                              DATETIME2 (7)   NULL,
    [is_current]                                                    BIT             NULL,
    [NUUDL_ValidFrom]                                               DATETIME2 (7)   NULL,
    [NUUDL_ValidTo]                                                 DATETIME2 (7)   NULL,
    [NUUDL_IsCurrent]                                               BIT             NULL,
    [NUUDL_ID]                                                      BIGINT          NOT NULL,
    [NUUDL_CuratedBatchID]                                          BIGINT          NULL,
    [DWIsCurrent]                                                   BIT             NULL,
    [DWValidFromDate]                                               DATETIME2 (7)   NOT NULL,
    [DWValidToDate]                                                 DATETIME2 (7)   NULL,
    [DWCreatedDate]                                                 DATETIME2 (7)   NULL,
    [DWModifiedDate]                                                DATETIME2 (7)   NULL,
    [DWIsDeletedInSource]                                           BIT             NULL,
    [DWDeletedInSourceDate]                                         DATETIME2 (7)   NULL,
    CONSTRAINT [PK_qssnrmlquote_History] PRIMARY KEY NONCLUSTERED ([NUUDL_ID] ASC, [DWValidFromDate] ASC)
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_qssnrmlquote_History]
    ON [sourceNuudlNetCracker].[qssnrmlquote_History];

