


CREATE VIEW [sourceNuudlNetCrackerView].[ibsitemshistory_History]
AS
SELECT 
	a.[id] ,
	a.[version] ,
	a.[schema_version] ,
	a.[active_from] ,
	a.[active_to] ,
	CAST(a.active_from AT TIME ZONE 'UTC' AT TIME ZONE 'Central European Standard Time' as datetime) [active_from_CET],
	CAST(a.[active_to] AT TIME ZONE 'UTC' AT TIME ZONE 'Central European Standard Time' as datetime) [active_to_CET],
	a.[is_snapshot] ,
	a.[state] ,
	a.[idempotency_key] ,
	a.[is_deleted] ,
	a.[last_modified_ts] ,
	a.[item_json_appliedBusinessBarringId] ,
	a.[is_current] ,
	a.[NUUDL_ValidTo] ,
	a.[item_json_appliedByBusinessRuleId] ,
	a.[NUUDL_ValidFrom] ,
	a.[NUUDL_IsCurrent] ,
	a.[item_json_creationDate] ,
	a.[item_json_customerCategoryId] ,
	a.[item_json_customerId] ,
	a.[item_json_disconnectionReason] ,
	a.[item_json_disconnectionReasonDescription] ,
	a.[item_json_distributionChannelId] ,
	a.[item_json_effectiveDate] ,
	a.[item_json_expirationDate] ,
	a.[item_json_id] ,
	a.[item_json_marketId] ,
	a.[item_json_marketingBundleComponentId] ,
	a.[item_json_name] ,
	a.[item_json_offeringId] ,
	a.[item_json_offeringName] ,
	a.[item_json_originalExpirationDate] ,
	a.[item_json_overrideMode] ,
	a.[item_json_parentId] ,
	a.[item_json_previousBusinessGroupId] ,
	a.[item_json_productFamilyId] ,
	a.[item_json_productFamilyName] ,
	a.[item_json_productOrderId] ,
	a.[item_json_prohibitManualRemoval] ,
	a.[item_json_quoteId] ,
	a.[item_json_rootId] ,
	a.[item_json_startDate] ,
	a.[item_json_state] ,
	a.[item_json_suspended] ,
	a.[item_json_terminationDate] ,
	a.[item_json_type] ,
	a.[item_json_accountRef_json_name] ,
	a.[item_json_accountRef_json_refId] ,
	a.[item_json_accountRef_json_refType] ,
	a.[item_json_agreementRef_json_agreementType] ,
	a.[item_json_agreementRef_json_name] ,
	a.[item_json_agreementRef_json_refId] ,
	a.[item_json_businessBarringRecords_json_businessBarringSpecificationId] ,
	a.[item_json_businessBarringRecords_json_id] ,
	a.[item_json_businessBarringRecords_json_name] ,
	a.[item_json_businessBarringRecords_json_validFrom] ,
	a.[item_json_businessBarringRecords_json_validTo] ,
	a.[item_json_businessGroup_json_id] ,
	a.[item_json_businessGroup_json_marketingBundleId] ,
	a.[item_json_businessGroup_json_name] ,
	a.[item_json_businessGroup_json_type] ,
	a.[item_json_characteristics_json_attributeId] ,
	a.[item_json_characteristics_json_name] ,
	a.[item_json_characteristics_json_offeringCharId] ,
	a.[item_json_characteristics_json_productSpecCharId] ,
	a.[item_json_characteristics_json_value] ,
	a.[item_json_extendedAttributes_json_key] ,
	a.[item_json_extendedAttributes_json_value] ,
	a.[item_json_prices_json_id] ,
	a.[item_json_prices_json_type] ,
	a.[item_json_prices_json_validFrom] ,
	a.[item_json_prices_json_validTo] ,
	a.[item_json_productSpecificationRef_json_id] ,
	a.[item_json_productSpecificationRef_json_name] ,
	a.[item_json_productSpecificationRef_json_version] ,
	a.[item_json_realizingServiceRefs_json_id] ,
	a.[item_json_realizingServiceRefs_json_name] ,
	a.[item_json_realizingServiceRefs_json_refId] ,
	a.[item_json_realizingServiceRefs_json_role] ,
	a.[item_json_relatedPartyRef_json_name] ,
	a.[item_json_relatedPartyRef_json_refId] ,
	a.[item_json_relatedPartyRef_json_referredType] ,
	a.[item_json_relatedPartyRef_json_role] ,
	a.[item_json_relatedPartyRef_json_userOfService] ,
	a.[item_json_technicalBarringRecords_json_barringType] ,
	a.[item_json_technicalBarringRecords_json_businessBarringRecordId] ,
	a.[item_json_technicalBarringRecords_json_id] ,
	a.[item_json_technicalBarringRecords_json_technicalBarringSpecificationId] ,
	a.[item_json_technicalBarringRecords_json_validFrom] ,
	a.[item_json_technicalBarringRecords_json_validTo] ,
	a.[item_json_prices_json_alterationPrices_json_alterationOnSuspendedPrice] ,
	a.[item_json_prices_json_alterationPrices_json_discountId] ,
	a.[item_json_prices_json_alterationPrices_json_id] ,
	a.[item_json_prices_json_alterationPrices_json_priceAlterationType] ,
	a.[item_json_prices_json_alterationPrices_json_reason] ,
	a.[item_json_prices_json_alterationPrices_json_state] ,
	a.[item_json_prices_json_alterationPrices_json_ticketId] ,
	a.[item_json_prices_json_alterationPrices_json_type] ,
	a.[item_json_prices_json_alterationPrices_json_validFrom] ,
	a.[item_json_prices_json_alterationPrices_json_validTo] ,
	a.[NUUDL_ID] ,
	a.[NUUDL_CuratedBatchID] 
	,a.[DWIsCurrent]
	,a.[DWValidFromDate]
	,a.[DWValidToDate]
	,a.[DWCreatedDate]
	,a.[DWModifiedDate]
	,a.[DWIsDeletedInSource]
	,a.[DWDeletedInSourceDate]
FROM [sourceNuudlNetCracker].[ibsitemshistory_History] a
LEFT JOIN [sourceNuudlNetCracker].[ibsitemshistory_History_Filter] b ON b.id = a.id
WHERE DWIsCurrent = 1
	AND b.id IS NULL