
CREATE VIEW [sourceNuudlNetCrackerView].[ibsitemshistory_History]
AS
SELECT 
	[id] ,
	[version] ,
	[schema_version] ,
	[active_from] ,
	[active_to] ,
	[is_snapshot] ,
	[state] ,
	[idempotency_key] ,
	[is_deleted] ,
	[last_modified_ts] ,
	[is_current] ,
	[item_json_appliedBusinessBarringId] ,
	[item_json_appliedByBusinessRuleId] ,
	[NUUDL_ValidTo] ,
	[NUUDL_ValidFrom] ,
	[NUUDL_IsCurrent] ,
	[item_json_creationDate] ,
	[item_json_customerCategoryId] ,
	[item_json_customerId] ,
	[item_json_disconnectionReason] ,
	[item_json_disconnectionReasonDescription] ,
	[item_json_distributionChannelId] ,
	[item_json_effectiveDate] ,
	[item_json_expirationDate] ,
	[item_json_id] ,
	[item_json_marketId] ,
	[item_json_marketingBundleComponentId] ,
	[item_json_name] ,
	[item_json_offeringId] ,
	[item_json_offeringName] ,
	[item_json_originalExpirationDate] ,
	[item_json_overrideMode] ,
	[item_json_parentId] ,
	[item_json_previousBusinessGroupId] ,
	[item_json_productFamilyId] ,
	[item_json_productFamilyName] ,
	[item_json_productOrderId] ,
	[item_json_prohibitManualRemoval] ,
	[item_json_quoteId] ,
	[item_json_rootId] ,
	[item_json_startDate] ,
	[item_json_state] ,
	[item_json_suspended] ,
	[item_json_terminationDate] ,
	[item_json_type] ,
	[item_json_accountRef_json_name] ,
	[item_json_accountRef_json_refId] ,
	[item_json_accountRef_json_refType] ,
	[item_json_agreementRef_json_agreementType] ,
	[item_json_agreementRef_json_name] ,
	[item_json_agreementRef_json_refId] ,
	[item_json_businessBarringRecords_json_businessBarringSpecificationId] ,
	[item_json_businessBarringRecords_json_id] ,
	[item_json_businessBarringRecords_json_name] ,
	[item_json_businessBarringRecords_json_validFrom] ,
	[item_json_businessBarringRecords_json_validTo] ,
	[item_json_businessGroup_json_id] ,
	[item_json_businessGroup_json_marketingBundleId] ,
	[item_json_businessGroup_json_name] ,
	[item_json_businessGroup_json_type] ,
	[item_json_characteristics_json_attributeId] ,
	[item_json_characteristics_json_name] ,
	[item_json_characteristics_json_offeringCharId] ,
	[item_json_characteristics_json_productSpecCharId] ,
	[item_json_characteristics_json_value] ,
	[item_json_extendedAttributes_json_key] ,
	[item_json_extendedAttributes_json_value] ,
	[item_json_prices_json_id] ,
	[item_json_prices_json_type] ,
	[item_json_prices_json_validFrom] ,
	[item_json_prices_json_validTo] ,
	[item_json_productSpecificationRef_json_id] ,
	[item_json_productSpecificationRef_json_name] ,
	[item_json_productSpecificationRef_json_version] ,
	[item_json_realizingServiceRefs_json_id] ,
	[item_json_realizingServiceRefs_json_name] ,
	[item_json_realizingServiceRefs_json_refId] ,
	[item_json_realizingServiceRefs_json_role] ,
	[item_json_relatedPartyRef_json_name] ,
	[item_json_relatedPartyRef_json_refId] ,
	[item_json_relatedPartyRef_json_referredType] ,
	[item_json_relatedPartyRef_json_role] ,
	[item_json_relatedPartyRef_json_userOfService] ,
	[item_json_technicalBarringRecords_json_barringType] ,
	[item_json_technicalBarringRecords_json_businessBarringRecordId] ,
	[item_json_technicalBarringRecords_json_id] ,
	[item_json_technicalBarringRecords_json_technicalBarringSpecificationId] ,
	[item_json_technicalBarringRecords_json_validFrom] ,
	[item_json_technicalBarringRecords_json_validTo] ,
	[item_json_prices_json_alterationPrices_json_alterationOnSuspendedPrice] ,
	[item_json_prices_json_alterationPrices_json_discountId] ,
	[item_json_prices_json_alterationPrices_json_id] ,
	[item_json_prices_json_alterationPrices_json_priceAlterationType] ,
	[item_json_prices_json_alterationPrices_json_reason] ,
	[item_json_prices_json_alterationPrices_json_state] ,
	[item_json_prices_json_alterationPrices_json_ticketId] ,
	[item_json_prices_json_alterationPrices_json_type] ,
	[item_json_prices_json_alterationPrices_json_validFrom] ,
	[item_json_prices_json_alterationPrices_json_validTo] ,
	[NUUDL_ID] ,
	[NUUDL_CuratedBatchID] 
	,[DWIsCurrent]
	,[DWValidFromDate]
	,[DWValidToDate]
	,[DWCreatedDate]
	,[DWModifiedDate]
	,[DWIsDeletedInSource]
	,[DWDeletedInSourceDate]
FROM [sourceNuudlNetCracker].[ibsitemshistory_History]
WHERE DWIsCurrent = 1