CREATE VIEW [dimView].[Address] 
AS
SELECT
	[AddressID]
	,[AddressKey] AS [AddressKey]
	,[Street1] AS [Street1]
	,[Street2] AS [Street2]
	,[Postcode] AS [Postcode]
	,[City] AS [City]
	,[Floor] AS [Floor]
	,[Suite] AS [Suite]
	,[NAMID]
	,[DarId]
	,[MadId]
	,[KvhxId]
	,[DWIsCurrent]
	,[DWValidFromDate]
	,[DWValidToDate]
	,[DWCreatedDate]
	,[DWModifiedDate]
	,[DWIsDeleted]
	
FROM [dim].[Address]