CREATE VIEW [dimView].[FAM Chipper Incident] 
AS
SELECT
	[FAM_ChipperIncidentID]
	,[FAM_ChipperIncidentKey] AS [F A M_ Chipper Incident Key]
	,[StartDate] AS [Start Date]
	,[CreatedDate] AS [Created Date]
	,[UpdatedDate] AS [Updated Date]
	,[ReportedDate] AS [Reported Date]
	,[ResolvedDate] AS [Resolved Date]
	,[CustomerEmailAdress] AS [Customer Email Adress]
	,[CustomerPhoneNumber] AS [Customer Phone Number]
	,[CustomerContactName] AS [Customer Contact Name]
	,[CustomerIDCode] AS [Customer I D Code]
	,[Impact] AS [Impact]
	,[Description] AS [Description]
	,[Type] AS [Type]
	,[ItemLidCode] AS [Item Lid Code]
	,[SLAIDCode] AS [S L A I D Code]
	,[Status] AS [Status]
	,[Subject] AS [Subject]
	,[ProductIDCode] AS [Product I D Code]
	,[Comments] AS [Comments]
	,[Tags] AS [Tags]
	,[PickedDate] AS [Picked Date]
	,[ClosedDate] AS [Closed Date]
	,[AssigneeCreated] AS [Assignee Created]
	,[AssigneePicked] AS [Assignee Picked]
	,[AssigneeResolved] AS [Assignee Resolved]
	,[IncidentCode] AS [Incident Code]
	,[OutageIncidentCode] AS [Outage Incident Code]
	,[DWIsCurrent]
	,[DWValidFromDate]
	,[DWValidToDate]
	,[DWCreatedDate]
	,[DWModifiedDate]
	,[DWIsDeleted]
	
FROM [dim].[FAM_ChipperIncident]