CREATE VIEW [dimView].[Legacy Product] 
AS
SELECT
	[Legacy_ProductID]
	,[Legacy_ProductKey] AS [Legacy Product Key]
	,[ProductName] AS [Product Name]
	,[ProductTypeName] AS [Product Type Name]
	,[ProductTypeUpdated] AS [Product Type Updated]
	,[ProductMainCategoryName] AS [Product Main Category Name]
	,[ProductCategoryName] AS [Product Category Name]
	,[ProductSubCategoryName] AS [Product Sub Category Name]
	,[ProductSubCategorySplitName] AS [Product Sub Category Split Name]
	,[ProductWeight] AS [Product Weight]
	,[ProductBrandCategoryName] AS [Product Brand Category Name]
	,[ProductTechnologyName] AS [Product Technology Name]
	,[ProductGroupCode] AS [Product Group Code]
	,[ProductGroupName] AS [Product Group Name]
	,[Legacy_ProductIsCurrent] AS [Legacy Product Is Current]
	,[Legacy_ProductValidFromDate] AS [Legacy Product Valid From Date]
	,[Legacy_ProductValidToDate] AS [Legacy Product Valid To Date]
	,[DWIsCurrent]
	,[DWValidFromDate]
	,[DWValidToDate]
	,[DWCreatedDate]
	,[DWModifiedDate]
	,[DWIsDeleted]
	
FROM [dim].[Legacy_Product]