CREATE VIEW [dimView].[Legacy Customer] 
AS
SELECT
	[Legacy_CustomerID]
	,[Legacy_CustomerKey] AS [Legacy_ Customer Key]
	,[CustomerCode] AS [Customer Code]
	,[CustomerFirstname] AS [Customer Firstname]
	,[CustomerLastName] AS [Customer Last Name]
	,[CustomerBusinessName1] AS [Customer Business Name1]
	,[CustomerBusinessName2] AS [Customer Business Name2]
	,[CustomerNameLong] AS [Customer Name Long]
	,[CustomerCategory] AS [Customer Category]
	,[CustomerCVRCode] AS [Customer C V R Code]
	,[CustomerCVRAbroadCode] AS [Customer C V R Abroad Code]
	,[CustomerBirthDate] AS [Customer Birth Date]
	,[CustomerGender] AS [Customer Gender]
	,[CustomerStatus] AS [Customer Status]
	,[Legacy_CustomerIsCurrent] AS [Legacy_ Customer Is Current]
	,[Legacy_CustomerValidFromDate] AS [Legacy_ Customer Valid From Date]
	,[Legacy_CustomerValidToDate] AS [Legacy_ Customer Valid To Date]
	,[DWIsCurrent]
	,[DWValidFromDate]
	,[DWValidToDate]
	,[DWCreatedDate]
	,[DWModifiedDate]
	,[DWIsDeleted]
	
FROM [dim].[Legacy_Customer]