CREATE VIEW [dimView].[PhoneDetail] 
AS
SELECT
	[PhoneDetailID]
	,[PhoneDetailkey] AS [PhoneDetailkey]
	,[PhoneStatus] AS [PhoneStatus]
	,[PhoneCategory] AS [PhoneCategory]
	,[PortedIn] AS [PortedIn]
	,[PortedOut] AS [PortedOut]
	,[PortedInFrom] AS [PortedInFrom]
	,[PortedOutTo] AS [PortedOutTo]
	,[PhoneDetailValidFromDate] AS [PhoneDetailValidFromDate]
	,[PhoneDetailValidToDate] AS [PhoneDetailValidToDate]
	,[PhoneDetailIsCurrent] AS [PhoneDetailIsCurrent]
	,[DWIsCurrent]
	,[DWValidFromDate]
	,[DWValidToDate]
	,[DWCreatedDate]
	,[DWModifiedDate]
	,[DWIsDeleted]
	
FROM [dim].[PhoneDetail]