CREATE VIEW [dimView].[QuoteItem] 
AS
SELECT
	[QuoteItemID]
	,[QuoteKey] AS [QuoteKey]
	,[QuoteItemKey] AS [QuoteItemKey]
	,[QuoteItemName] AS [QuoteItemName]
	,[NRC_ActivationBasePriceExclTax] AS [NRC_ActivationBasePriceExclTax]
	,[NRC_DeactivationBasePriceExclTax] AS [NRC_DeactivationBasePriceExclTax]
	,[NRC_DicsountPriceExclTax] AS [NRC_DicsountPriceExclTax]
	,[NRC_ReplacementPriceExclTax] AS [NRC_ReplacementPriceExclTax]
	,[NRC_ActivationBasePriceInclTax] AS [NRC_ActivationBasePriceInclTax]
	,[NRC_DeactivationBasePriceInclTax] AS [NRC_DeactivationBasePriceInclTax]
	,[NRC_DicsountPriceInclTax] AS [NRC_DicsountPriceInclTax]
	,[NRC_ReplacementPriceInclTax] AS [NRC_ReplacementPriceInclTax]
	,[RecurrentType] AS [RecurrentType]
	,[RC_BasePriceExclTax] AS [RC_BasePriceExclTax]
	,[RC_DicsountPriceExclTax] AS [RC_DicsountPriceExclTax]
	,[RC_ReplacementPriceExclTax] AS [RC_ReplacementPriceExclTax]
	,[RC_BasePriceInclTax] AS [RC_BasePriceInclTax]
	,[RC_DicsountPriceInclTax] AS [RC_DicsountPriceInclTax]
	,[RC_ReplacementPriceInclTax] AS [RC_ReplacementPriceInclTax]
	,[CommitmentDuration] AS [CommitmentDuration]
	,[CommitmentDurationUnits] AS [CommitmentDurationUnits]
	,[DWIsCurrent]
	,[DWValidFromDate]
	,[DWValidToDate]
	,[DWCreatedDate]
	,[DWModifiedDate]
	,[DWIsDeleted]
	
FROM [dim].[QuoteItem]