CREATE VIEW [dimView].[Subscription] 
AS
SELECT
	[SubscriptionID]
	,[SubscriptionKey] AS [SubscriptionKey]
	,[SubscriptionOriginalKey] AS [SubscriptionOriginalKey]
	,[FamilyBundle] AS [FamilyBundle]
	,[BundleType] AS [BundleType]
	,[SubscriptionValidFromDate] AS [SubscriptionValidFromDate]
	,[SubscriptionValidToDate] AS [SubscriptionValidToDate]
	,[SubscriptionIsCurrent] AS [SubscriptionIsCurrent]
	,[BundleTypeSimple] AS [BundleTypeSimple]
	,[DWIsCurrent]
	,[DWValidFromDate]
	,[DWValidToDate]
	,[DWCreatedDate]
	,[DWModifiedDate]
	,[DWIsDeleted]
	
FROM [dim].[Subscription]