CREATE TABLE [stage].[Fact_ChipperIncidents] (
    [CalendarKey]                                  DATE           NULL,
    [CalendarPickedKey]                            DATE           NULL,
    [CalendarDerivedKey]                           DATE           NULL,
    [CalendarCancelledKey]                         DATE           NULL,
    [CalendarClosedKey]                            DATE           NULL,
    [Legacy_EmployeeKey]                           NVARCHAR (55)  NULL,
    [Legacy_CustomerKey]                           NVARCHAR (55)  NULL,
    [Legacy_ProductKey]                            NVARCHAR (55)  NULL,
    [FAM_SalesChannelKey]                          NVARCHAR (55)  NULL,
    [FAM_ChipperStatusKey]                         NVARCHAR (55)  NULL,
    [FAM_ChipperIncidentKey]                       NVARCHAR (55)  NULL,
    [FAM_InfrastructureKey]                        NVARCHAR (55)  NULL,
    [FAM_TechnologyKey]                            NVARCHAR (55)  NULL,
    [FAM_OpenIncidentsGroupKey]                    NVARCHAR (55)  NULL,
    [FAM_OpenIncidentsGroupHandleKey]              NVARCHAR (55)  NULL,
    [FAM_OpenIncidentsGroupInstallationToErrorKey] NVARCHAR (55)  NULL,
    [IncidentCode]                                 NVARCHAR (55)  NULL,
    [IncidentLidCode]                              NVARCHAR (55)  NULL,
    [IncidentProduct]                              NVARCHAR (55)  NULL,
    [IncidentCreated]                              INT            NULL,
    [IncidentClosed]                               INT            NULL,
    [IncidentPicked]                               INT            NULL,
    [IncidentDerived]                              INT            NULL,
    [IncidentCancelled]                            INT            NULL,
    [IncidentResponseTime]                         INT            NULL,
    [IncidentDaysOpen]                             INT            NULL,
    [IncidentDaysToHandle]                         INT            NULL,
    [IncidentRepeating3Days]                       INT            NOT NULL,
    [IncidentRepeating14Days]                      INT            NOT NULL,
    [TechnologyInstalled]                          NVARCHAR (55)  NULL,
    [DaysFromInstallationToError]                  INT            NULL,
    [PercentOfIncidents3DaysFromInstallation]      DECIMAL (7, 4) NULL,
    [PercentOfIncidents14DaysFromInstallation]     DECIMAL (7, 4) NULL,
    [DWCreatedDate]                                DATETIME       NOT NULL
);

