CREATE TABLE [sourceCubusMasterData].[DimEmployee] (
    [EmployeeKey]                 INT            NOT NULL,
    [SRC_DW_ID_DimEmployeeWork]   INT            NULL,
    [SRC_DW_AuditKey]             INT            NULL,
    [SRC_DW_Batch_Created_ID]     INT            NULL,
    [SRC_DW_Batch_Updated_ID]     INT            NULL,
    [SRC_DW_CreateDate]           DATETIME       NULL,
    [SRC_DW_UpdateDate]           DATETIME       NULL,
    [SRC_DW_Valid_From]           DATETIME       NULL,
    [SRC_DW_Valid_To]             DATETIME       NULL,
    [SRC_DW_EarlyArrived]         BIT            NULL,
    [SRC_DW_IsCurrent]            BIT            NULL,
    [SRC_DW_IsDeleted]            BIT            NULL,
    [SRC_DW_CRC]                  NVARCHAR (250) NULL,
    [Source_Updated_TS]           DATETIME       NULL,
    [Source_Created_TS]           DATETIME       NULL,
    [Source_Updated_By]           NVARCHAR (250) NULL,
    [Source_Created_By]           NVARCHAR (250) NULL,
    [EmployeeID]                  NVARCHAR (11)  NULL,
    [EmployeeRecord]              INT            NULL,
    [SourceSystem]                NVARCHAR (50)  NULL,
    [JobIndicator]                NVARCHAR (2)   NULL,
    [EmployeeStatus]              NVARCHAR (2)   NULL,
    [Sex]                         NVARCHAR (2)   NULL,
    [BirthDate]                   DATETIME2 (7)  NULL,
    [FirstName]                   NVARCHAR (30)  NULL,
    [LastName]                    NVARCHAR (30)  NULL,
    [Name]                        NVARCHAR (92)  NULL,
    [LocalPhone]                  NVARCHAR (24)  NULL,
    [MobilePhone]                 NVARCHAR (24)  NULL,
    [FAX]                         NVARCHAR (24)  NULL,
    [WorkplacePhone]              NVARCHAR (24)  NULL,
    [AlternativePhone]            NVARCHAR (24)  NULL,
    [RoomNumber]                  NVARCHAR (30)  NULL,
    [PostalRoomNumber]            NVARCHAR (30)  NULL,
    [Email]                       NVARCHAR (70)  NULL,
    [UserID]                      NVARCHAR (30)  NULL,
    [SeniorityDate]               DATETIME2 (7)  NULL,
    [AnniversaryDate]             DATETIME2 (7)  NULL,
    [StandardHours]               DECIMAL (6, 2) NULL,
    [OriginalHireDate]            DATETIME2 (7)  NULL,
    [LatestHireDate]              DATETIME2 (7)  NULL,
    [TerminationDate]             DATETIME2 (7)  NULL,
    [LocationID]                  NVARCHAR (10)  NULL,
    [WorkAddress]                 NVARCHAR (55)  NULL,
    [WorkZipCode]                 NVARCHAR (12)  NULL,
    [WorkPostalDistrict]          NVARCHAR (25)  NULL,
    [BusinessTitleCode]           NVARCHAR (6)   NULL,
    [BusinessTitle]               NVARCHAR (30)  NULL,
    [BusinessTitleShort]          NVARCHAR (10)  NULL,
    [BusinessStatisticsCode]      NVARCHAR (6)   NULL,
    [BusinessFunction]            NVARCHAR (30)  NULL,
    [JobStatus]                   NVARCHAR (30)  NULL,
    [JobCode]                     NVARCHAR (6)   NULL,
    [JobCodeDescription]          NVARCHAR (30)  NULL,
    [EmployeeClass]               NVARCHAR (30)  NULL,
    [SalaryAdminPlan]             NVARCHAR (4)   NULL,
    [SalaryGrade]                 NVARCHAR (30)  NULL,
    [PayGroup]                    NVARCHAR (3)   NULL,
    [SalaryType]                  NVARCHAR (30)  NULL,
    [EmployeeType]                NVARCHAR (30)  NULL,
    [DepartmentID]                NVARCHAR (10)  NULL,
    [DepartmentDescription]       NVARCHAR (30)  NULL,
    [DepartmentDescriptionShort]  NVARCHAR (10)  NULL,
    [ManagerEmployeeID]           NVARCHAR (11)  NULL,
    [AONR]                        NVARCHAR (4)   NULL,
    [Company]                     NVARCHAR (3)   NULL,
    [CompanyDescription]          NVARCHAR (30)  NULL,
    [CompanyDescriptionShort]     NVARCHAR (10)  NULL,
    [EmployeeTypeCode]            NVARCHAR (10)  NULL,
    [TerminationInfo]             NVARCHAR (15)  NULL,
    [EmployeeStatusDescription]   NVARCHAR (30)  NULL,
    [SexDescription]              NVARCHAR (30)  NULL,
    [SkillGroup]                  NVARCHAR (10)  NULL,
    [IsManager]                   NVARCHAR (3)   NULL,
    [SquadID]                     NVARCHAR (7)   NULL,
    [SquadDescription]            NVARCHAR (60)  NULL,
    [SquadDescriptionShort]       NVARCHAR (10)  NULL,
    [IsAgileCoach]                NVARCHAR (3)   NULL,
    [IsProductOwner]              NVARCHAR (3)   NULL,
    [ApprovedEmailDomain]         NVARCHAR (3)   NULL,
    [ChapterAreaID]               NVARCHAR (12)  NULL,
    [ChapterAreaDescription]      NVARCHAR (30)  NULL,
    [ChapterAreaDescriptionShort] NVARCHAR (10)  NULL,
    [DWCreatedDate]               DATETIME2 (7)  DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_DimEmployee] PRIMARY KEY NONCLUSTERED ([EmployeeKey] ASC)
);


GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_DimEmployee]
    ON [sourceCubusMasterData].[DimEmployee];

