CREATE TABLE [dim].[Calendar](
	[CalendarID] [int] NOT NULL,
	[CalendarKey] [date] NULL,
	[CalendarDate] [date] NULL,
	[DayNumber] [int] NULL,
	[WeekCode] [int] NULL,
	[WeekNumber] [int] NULL,
	[WeekName] [nvarchar](20) NULL,
	[WeekYear] [int] NULL,
	[WeekDayNumber] [smallint] NULL,
	[WeekDayName] [nvarchar](10) NULL,
	[MonthCode] [int] NULL,
	[MonthNumber] [int] NULL,
	[MonthName] [nvarchar](20) NULL,
	[MonthShort] [nvarchar](3) NULL,
	[MonthLong] [nvarchar](12) NULL,
	[QuarterCode] [int] NULL,
	[QuarterNumber] [int] NULL,
	[QuarterName] [nvarchar](20) NULL,
	[Quarter] [nvarchar](2) NULL,
	[Year] [int] NULL,
	[FiscalMonthCode] [int] NULL,
	[FiscalMonthNumber] [int] NULL,
	[FiscalMonthName] [nvarchar](20) NULL,
	[FiscalQuarterCode] [int] NULL,
	[FiscalQuarterNumber] [int] NULL,
	[FiscalQuarterName] [nvarchar](20) NULL,
	[FiscalYear] [int] NULL,
	[FiscalYearName] [varchar](10) NULL,
	[FirstDateofYear] [date] NULL,
	[LastDateofYear] [date] NULL,
	[FirstDateofQuarter] [date] NULL,
	[LastDateofQuarter] [date] NULL,
	[FirstDateofMonth] [date] NULL,
	[LastDateofMonth] [date] NULL,
	[FirstDateofWeek] [date] NULL,
	[LastDateofWeek] [date] NULL,
	[CurrentYear] [smallint] NULL,
	[CurrentQuarter] [smallint] NULL,
	[CurrentMonth] [smallint] NULL,
	[CurrentWeek] [smallint] NULL,
	[CurrentDay] [int] NULL,
	[IsToday] [bit] NULL,
	[IsWeekend] [bit] NULL,
	[IsHoliday] [bit] NULL,
	[HolidayName] [varchar](20) NULL,
	[SpecialDays] [varchar](20) NULL,
	[CalendarIsFutureFlag] [bit] NULL,
	[DWModifiedDate] [datetime] NULL,
    PRIMARY KEY CLUSTERED ([CalendarID] ASC)
);



