CREATE TABLE [dim].[FAM_ChipperIncident] (
    [FAM_ChipperIncidentID]  INT            IDENTITY (1, 1) NOT NULL,
    [FAM_ChipperIncidentKey] NVARCHAR (500) NULL,
    [StartDate]              DATE           NULL,
    [CreatedDate]            DATE           NULL,
    [UpdatedDate]            DATE           NULL,
    [ReportedDate]           DATE           NULL,
    [ResolvedDate]           DATE           NULL,
    [CustomerEmailAdress]    NVARCHAR (500) NULL,
    [CustomerPhoneNumber]    NVARCHAR (500) NULL,
    [CustomerContactName]    NVARCHAR (500) NULL,
    [CustomerIDCode]         NVARCHAR (500) NULL,
    [Impact]                 NVARCHAR (500) NULL,
    [Description]            NVARCHAR (MAX) NULL,
    [Type]                   NVARCHAR (500) NULL,
    [ItemLidCode]            NVARCHAR (500) NULL,
    [SLAIDCode]              NVARCHAR (500) NULL,
    [Status]                 NVARCHAR (500) NULL,
    [Subject]                NVARCHAR (500) NULL,
    [ProductIDCode]          NVARCHAR (500) NULL,
    [Comments]               NVARCHAR (MAX) NULL,
    [Tags]                   NVARCHAR (MAX) NULL,
    [PickedDate]             DATE           NULL,
    [ClosedDate]             DATE           NULL,
    [AssigneeCreated]        NVARCHAR (100) NULL,
    [AssigneePicked]         NVARCHAR (100) NULL,
    [AssigneeResolved]       NVARCHAR (100) NULL,
    [IncidentCode]           NVARCHAR (500) NULL,
    [OutageIncidentCode]     NVARCHAR (50)  NULL,
    [DWIsCurrent]            BIT            NOT NULL,
    [DWValidFromDate]        DATETIME2 (0)  NOT NULL,
    [DWValidToDate]          DATETIME2 (0)  NOT NULL,
    [DWCreatedDate]          DATETIME2 (0)  NOT NULL,
    [DWModifiedDate]         DATETIME2 (0)  NOT NULL,
    [DWIsDeleted]            BIT            NOT NULL,
    PRIMARY KEY CLUSTERED ([FAM_ChipperIncidentID] ASC),
    CONSTRAINT [NCI_FAM_ChipperIncident] UNIQUE NONCLUSTERED ([FAM_ChipperIncidentKey] ASC, [DWValidFromDate] ASC)
);

