name: Copy Files From Prod

on:  
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" 

jobs:
  dev:
    name: Copy Files From Prod to Dev
    environment:
      name: dev
    
    runs-on: windows-latest
    steps:

      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}     
        enable-AzPSSession: true       


    - name: Copy Files from Prod to Dev
      uses: azure/powershell@v1
      with:
        inlineScript: |
             ./Tools/AzCopy/CopyFiles.ps1 -SourceStorageAccount 'adlsdataestateprod' -TargetStorageAccount 'adlsdataestatedev' -SourceAccessKey ${{ secrets.AZURE_DATALAKE_STORAGE_KEY_PROD }} -TargetAccessKey ${{ secrets.AZURE_DATALAKE_STORAGE_KEY }} -TenantID ${{ secrets.AZURE_TENANT_ID }} -ClientID ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }} -ClientSecret ${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET }} -KeyVault "kv-dataestate-dev"
        azPSVersion: "latest"  

  test:
    name: Copy Files From Prod to Test
    environment:
      name: test
    
    runs-on: windows-latest
    steps:

      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}     
        enable-AzPSSession: true       


    - name: Copy Files from Prod to Test
      uses: azure/powershell@v1
      with:
        inlineScript: |
             ./Tools/AzCopy/CopyFiles.ps1 -SourceStorageAccount 'adlsdataestateprod' -TargetStorageAccount 'adlsdataestatetest' -SourceAccessKey ${{ secrets.AZURE_DATALAKE_STORAGE_KEY_PROD }} -TargetAccessKey ${{ secrets.AZURE_DATALAKE_STORAGE_KEY }} -TenantID ${{ secrets.AZURE_TENANT_ID }} -ClientID ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }} -ClientSecret ${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET }} -KeyVault "kv-dataestate-test"
        azPSVersion: "latest"   

