name: Release ADB Notebooks to Development

on:
  push:
    branches: 
      - 'development'
  workflow_dispatch:  

jobs:
  Deploy:
    name: Release ADB Notebooks to Development
    uses: ./.github/workflows/master_release_services.yml
    with:
      DeployToDev: false 
      DeployToTest: false 
      DeployToProd: false 
      DeployIaC: false 
      DeploySSMS: false
      DeployADF: false
      DeployADB: false
      DeployPBI: false
      DeployPBIModel: 'All' 
      DeployMetaData: false 
    secrets: inherit     
