name: Suspend SSAS Prod

on:
  workflow_dispatch:  

jobs:
  Deploy:
    name: Suspend SSAS 
    uses: ./.github/workflows/Template_tasks_prod.yml
    with:
      DeploySSMS: false
      DeployADF: false
      DeploySSAS: false
      SuspendSSAS: true
    secrets: inherit
